- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:CharacterPlaytimeRequirement # Lost Paradise - Time in start role (PE4HENIKA)
      tracker: Passenger
      min: 7200 # 2 hours
    # - !type:DepartmentTimeRequirement # Lost Paradise - return time limit
    #   department: Medical
    #   time: 54000 # 15 hrs
    #   inverted: true # stop playing intern if you're good at med!
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Medical
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining

- type: startingGear
  id: MedicalInternGear
  equipment:
    jumpsuit: UniformScrubsColorBlue # DeltaV - Intern starts with blue scrubs
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  # innerClothingSkirt: ClothingUniformJumpskirtColorWhite # DeltaV
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
