- type: job
  id: SAI
  name: job-name-sai
  description: job-description-sai
  playTimeTracker: JobSAI
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 14400
    - !type:DepartmentTimeRequirement
      department: Epistemics
      time: 14400
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 14400
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 14400
  icon: JobIconBorg
  supervisors: "весь экипаж"
  accessGroups:
    - AllAccess
  canBeAntag: false
  jobEntity: AICore
  alwaysUseSpawner: true
  joinNotifyCrew: true
