- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Robotics
  - Maintenance

- type: startingGear
  id: RoboticistGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: RoboticsPDA
    ears: ClothingHeadsetRobotics
    eyes: ClothingEyesHudDiagnostic
    belt: ClothingBeltUtilityEngineering


