name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Статус: Требуется одобрение"
        repo-token: "${{ secrets.BOT_TOKEN }}"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Статус: Ожидание изменений"
        repo-token: "${{ secrets.BOT_TOKEN }}"
