name: Publish-lostparadise

concurrency:
  group: publish-lostparadise

on:
  workflow_dispatch:

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANGELOG_DIR: Resources/Changelog/ChangelogLPP.yml
  PR_NUMBER: ${{ github.event.number }}
  CHANGELOG_DISCORD_WEBHOOK: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: 'recursive'

    - name: Download parts
      run: |
        git clone ${{ secrets.HUB_SEC_TOKEN }}
        mv Secrets/_PrivateResources/_Private Resources/Prototypes/
        mv Secrets/_PrivateResources/PERSONAL Resources/Textures/
        mv Secrets/_PrivateShared Content.Shared/_PrivateShared
        mv Secrets/_PrivateServer Content.Server/_PrivateServer
        mv Secrets/_PrivateClient Content.Client/_PrivateClient

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.0

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform linux-x64 --hybrid-acz

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"

    - name: Upload files to centcomm
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH }}
        port: ${{ secrets.PORT }}
        source: "release/${{ github.sha }}"
        target: "/var/www/wiki/builds_dir/builds/"
        strip_components: 1

    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH }}
        port: ${{ secrets.PORT }}
        script: pwsh /var/www/wiki/push.ps1 ${{ github.sha }}

    - name: Publish changelog
      run: Tools/actions_changelogs_since_last_run.py
